### ISSUE TITLE
pretty style for <table> elements

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/mysociety-docs-theme#13]
Current style renders tables with no borders.

I don't think there are any tables in the docs which are not tabulated data, so a border would be nice. 

Fancy-pantsy zebra striped rows and whatnot left to designers' discretion.

**Comment by zarino** [comment]
Looks like, if you give your table a class of "table" then it will have borders:

```
<table class="table">
  <tr>
    <td>I have</td>
    <td></td>
  <tr>
  <tr>
    <td colspan="2">borders!</td>
  </tr>
</table>
```

https://github.com/mysociety/mysociety-docs-theme/blob/30be94a907f0c291d3364a575f3956f9c80e9aed/sass/global.scss#L491-L503

**Comment by davewhiteland** [comment]
thanks for spotting this @zarino!
