### ISSUE TITLE
add "print" media query for beautiful off-line docs

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/mysociety-docs-theme#17]
Would be nice if we were knocking out the nav and footer for offline/printed docs

**Comment by stevenday** [comment]
@davewhiteland - who prints off code docs? (Genuine question)

**Comment by davewhiteland** [comment]
@stevenday Good point -- only a chump prints off code docs. But the underlying use case for this wasn't *code* docs -- the Alaveteli admin guide (and its FMS equivalents) are in this theme.

So the use case here is a non-technical admin printing out one of the pages that describes a common task and sticking it on their desk/noticeboard/wotsit.

(Also I think *just* knocking out the `nav` and `footer` is a fairly lightweight, high-gain change).


I created this issue in response to a suggestion that  a new FMS-related doc be published as a PDF whereas I believe it should be a page in the docs; if it pretty-printed then there's no argument for it being a PDF.

**Comment by davewhiteland** [comment]
Bumping this now I've added training material to fixmystreet.org that exists as a trinity of long web page, slide presentation, and printable document.
Tbh I came here to make this issue only to discover I already had :-)

> "(Also I think just knocking out the nav and footer is a fairly lightweight, high-gain change)."

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/mysociety-docs-theme/pull/18 – feedback welcome.

![screen shot 2015-10-28 at 16 23 47](https://cloud.githubusercontent.com/assets/739624/10795157/53e22d52-7d90-11e5-8721-71a907decd77.png)
