### ISSUE TITLE
Implement standard mySociety footer for docs sites (eg: alaveteli.org, fixmystreet.org)

### ISSUE THREAD

**Issue by dracos** [mysociety/mysociety-docs-theme#19]
See mysociety/sysadmin#676 for original discussion/design.

**Comment by zarino** [comment]
PR for shared styles on mysociety-docs-theme here: https://github.com/mysociety/mysociety-docs-theme/issues/21

Templates to implement the footer on alaveteli.org here: https://github.com/mysociety/alaveteli/pull/3241

Templates to implement the footer on fixmystreet.org here: https://github.com/mysociety/fixmystreet/pull/1397
